export const AVATAR: any = {
  doctor1: require("images/Avatar/doctor-1.png"),
  doctor2: require("images/Avatar/doctor-2.png"),
  doctor3: require("images/Avatar/doctor-3.png"),
  doctor4: require("images/Avatar/doctor-4.png"),
  doctor5: require("images/Avatar/doctor-5.png"),
  doctor6: require("images/Avatar/doctor-6.png"),
  doctor7: require("images/Avatar/doctor-7.png"),
  avatar1: require("images/Avatar/avatar-1.png"),
  avatar2: require("images/Avatar/avatar-2.png"),
  avatar3: require("images/Avatar/avatar-3.png"),
  avatar4: require("images/Avatar/avatar-4.png"),
  avatar5: require("images/Avatar/avatar-5.png"),
  avatar6: require("images/Avatar/avatar-6.png"),
  avatar7: require("images/Avatar/avatar-7.png"),
  avatar8: require("images/Avatar/avatar-8.png"),
  avatar9: require("images/Avatar/avatar_myra_douglas.png"),
  avatar10: require("images/Avatar/avatar_nancy_beck.png"),
  avatar11: require("images/Avatar/avatar_11.png"),
  avatar12: require("images/Avatar/avatar_12.png"),
  avatar13: require("images/Avatar/avatar_13.png"),
  bradley: require("images/Avatar/bradley.png"),
  sarah: require("images/Avatar/sarah.png"),
  wallace: require("images/Avatar/wallace.png"),
  joanna: require("images/Avatar/joanna.png"),
};
