export enum EnumWriteAnAnswer {
  WRITE_ANSWER = "WRITE_ANSWER",
  ADD_PRESCRIPTION = "ADD_PRESCRIPTION",
  DELETE_PRESCRIPTION = "DELETE_PRESCRIPTION",
  ADD_ATTACHED_FILES = "ADD_ATTACHED_FILES",
  DELETE_ATTACHED_FILES = "DELETE_ATTACHED_FILES",
  ADD_SHARE_INFO = "ADD_SHARE_INFO",
  DELETE_SHARE_INFO = "DELETE_SHARE_INFO",
}
